'use client';

// Renders a frozen report's stored markdown ([08-WKLY]).
//
// WHY THIS IS HAND-WRITTEN RATHER THAN A LIBRARY. Two reasons, and the second is the real one.
// The frontend carries four runtime dependencies on purpose, and this would be the fifth for one
// screen. More importantly, an archive is a promise that a report reads today as it read the day
// it was published — and a markdown library that changes its table or emphasis handling across a
// version bump would quietly break that promise on every historical report at once. The input is
// not arbitrary markdown: it is generated by `trading/reports/fmt.py`, whose entire vocabulary is
// headings, GFM tables, `-`/`*` lists, blockquotes, `**bold**`, `*italic*` and `` `code` ``. That
// is a closed set, and it is enumerated below.
//
// THE RULE THAT MATTERS: anything unrecognized is rendered as literal text, never dropped. If the
// reports gain a construct this does not know, the reader sees the raw line — ugly, and visibly
// so. Silently swallowing a published line is the one failure mode an archive cannot have, since
// nothing downstream would ever reveal it.
//
// No `dangerouslySetInnerHTML` anywhere: every node here is React-escaped.

import React from 'react';

/* ------------------------------------------------------------------ inline ---- */
// Order matters: `**bold**` must be tried before `*italic*`, or the emphasis parse eats the
// leading pair and renders a stray asterisk.
const INLINE = /(\*\*[^*\n]+\*\*|`[^`\n]+`|\*[^*\n]+\*)/g;

function inline(text: string, keyPrefix: string): React.ReactNode[] {
  const out: React.ReactNode[] = [];
  const parts = text.split(INLINE);
  parts.forEach((p, i) => {
    if (!p) return;
    const k = `${keyPrefix}-${i}`;
    if (p.startsWith('**') && p.endsWith('**') && p.length > 4) {
      out.push(<b key={k} style={{ color: 'var(--tx)' }}>{p.slice(2, -2)}</b>);
    } else if (p.startsWith('`') && p.endsWith('`') && p.length > 2) {
      out.push(
        <code key={k} className="px-1 py-0.5 rounded text-[11px]"
              style={{ background: 'var(--panel2)', color: 'var(--tx)' }}>
          {p.slice(1, -1)}
        </code>,
      );
    } else if (p.startsWith('*') && p.endsWith('*') && p.length > 2) {
      out.push(<i key={k}>{p.slice(1, -1)}</i>);
    } else {
      out.push(<React.Fragment key={k}>{p}</React.Fragment>);
    }
  });
  return out;
}

/* ------------------------------------------------------------------- blocks ---- */
const cells = (line: string) =>
  line.replace(/^\s*\|/, '').replace(/\|\s*$/, '').split('|').map((c) => c.trim());

// A GFM delimiter row: |---|---| or |:--|--:| . Only this marks the line above as a header.
const isDelim = (line: string) =>
  /^\s*\|?\s*:?-{2,}:?\s*(\|\s*:?-{2,}:?\s*)*\|?\s*$/.test(line) && line.includes('-');

const isRow = (line: string) => line.trimStart().startsWith('|');

// Numbers right-align; everything else left. Done by shape rather than by column config because
// the tables are generated and carry no alignment hints — and a column of right-aligned returns
// is the difference between a scannable table and a wall.
const numeric = (s: string) => /^[+\-−]?[$]?[\d,.]+\s*(%|bp|x)?$/.test(s.trim()) || s.trim() === 'n/a';

export function ReportMarkdown({ md }: { md: string }) {
  const lines = md.replace(/\r\n/g, '\n').split('\n');
  const out: React.ReactNode[] = [];
  let para: string[] = [];
  let list: string[] = [];
  let i = 0;

  const flushPara = () => {
    if (!para.length) return;
    // A single newline is kept as a LINE BREAK rather than collapsed, which is a deliberate
    // departure from strict markdown. The generator never hard-wraps — degradation bullets run
    // well past 150 characters on one line — so every newline it emits is one it meant, and the
    // same text delivered to Slack breaks there too. Collapsing them would run the monthly's
    // period line and its coverage note together into a sentence nobody wrote.
    const n = out.length;
    out.push(
      <p key={`p${n}`} className="text-[12.5px] leading-[1.65] mb-3"
         style={{ color: 'var(--tx-mut)' }}>
        {para.map((ln, k) => (
          <React.Fragment key={k}>
            {k > 0 && <br />}
            {inline(ln, `p${n}-${k}`)}
          </React.Fragment>
        ))}
      </p>,
    );
    para = [];
  };
  const flushList = () => {
    if (!list.length) return;
    out.push(
      <ul key={`u${out.length}`} className="mb-3 space-y-1.5">
        {list.map((it, n) => (
          <li key={n} className="text-[12.5px] leading-[1.6] pl-4 relative"
              style={{ color: 'var(--tx-mut)' }}>
            <span className="absolute left-0" style={{ color: 'var(--tx-dim)' }}>·</span>
            {inline(it, `u${out.length}-${n}`)}
          </li>
        ))}
      </ul>,
    );
    list = [];
  };
  const flush = () => { flushPara(); flushList(); };

  while (i < lines.length) {
    const line = lines[i];
    const t = line.trim();

    if (!t) { flush(); i += 1; continue; }

    // --- table: a run of pipe rows, with the delimiter deciding whether row 1 is a header ---
    if (isRow(line)) {
      flush();
      const block: string[] = [];
      while (i < lines.length && isRow(lines[i])) { block.push(lines[i]); i += 1; }
      const hasHead = block.length > 1 && isDelim(block[1]);
      const head = hasHead ? cells(block[0]) : null;
      const body = block.filter((b, n) => !isDelim(b) && !(hasHead && n === 0)).map(cells);
      out.push(
        <div key={`t${out.length}`} className="mb-4 overflow-x-auto">
          <table className="w-full text-[11.5px]" style={{ borderCollapse: 'collapse' }}>
            {head && (
              <thead>
                <tr>
                  {head.map((h, n) => (
                    <th key={n} className="text-left font-bold py-1.5 px-2 whitespace-nowrap"
                        style={{
                          color: 'var(--tx-dim)', borderBottom: '1px solid var(--border)',
                          textAlign: n && numeric(body[0]?.[n] ?? '') ? 'right' : 'left',
                        }}>
                      {h}
                    </th>
                  ))}
                </tr>
              </thead>
            )}
            <tbody>
              {body.map((r, n) => (
                <tr key={n}>
                  {r.map((c, m) => (
                    <td key={m} className="py-1.5 px-2 whitespace-nowrap"
                        style={{
                          color: 'var(--tx)', borderBottom: '1px solid var(--border-soft)',
                          textAlign: m && numeric(c) ? 'right' : 'left',
                          fontVariantNumeric: 'tabular-nums',
                        }}>
                      {inline(c, `t${out.length}-${n}-${m}`)}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>,
      );
      continue;
    }

    // --- headings ---
    const h = /^(#{1,6})\s+(.*)$/.exec(t);
    if (h) {
      flush();
      const lvl = h[1].length;
      const size = lvl === 1 ? 'text-[15px]' : lvl === 2 ? 'text-[13px]' : 'text-[12px]';
      out.push(
        <div key={`h${out.length}`}
             className={`${size} font-bold tracking-tight mb-2 ${out.length ? 'mt-5' : ''}`}
             style={{ color: 'var(--tx)' }}>
          {inline(h[2], `h${out.length}`)}
        </div>,
      );
      i += 1; continue;
    }

    // --- blockquote ---
    if (t.startsWith('>')) {
      flush();
      const block: string[] = [];
      while (i < lines.length && lines[i].trim().startsWith('>')) {
        block.push(lines[i].trim().replace(/^>\s?/, '')); i += 1;
      }
      out.push(
        <div key={`q${out.length}`} className="mb-3 pl-3 text-[12px] leading-[1.6]"
             style={{ borderLeft: '2px solid var(--border)', color: 'var(--tx-mut)' }}>
          {inline(block.join(' '), `q${out.length}`)}
        </div>,
      );
      continue;
    }

    // --- list item. `* ` only counts as a bullet with the space: `*emphasis*` is not a list. ---
    const li = /^[-*]\s+(.*)$/.exec(t);
    if (li) { flushPara(); list.push(li[1]); i += 1; continue; }

    // --- anything else is prose, INCLUDING constructs this renderer does not know. Falling
    //     through to text is deliberate: a visible raw line beats a vanished one.
    flushList();
    para.push(t);
    i += 1;
  }
  flush();

  return <div>{out}</div>;
}
